[features]
seeds = false
skip-lint = false

[programs.devnet]
nft_lend_borrow = "9G1FU3sSmVtz1xQHRwkTfFHXfNj29p62r9VAxKNdocN7"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
